POST http://127.0.0.1:6969/ask
Content-Type: application/json

{
  "question": "How do I run JS code in VS Code? I dont want to use debugging."
}

###

POST http://127.0.0.1:6969/add_urls
Content-Type: application/json

{
  "urls": ["https://stackoverflow.com/questions/31778413/run-javascript-in-visual-studio-code"]
}

