POST http://127.0.0.1:6969/ask
Content-Type: application/json

{
  "question": "Is there a grant for creating a woodland?"
}

###

POST http://127.0.0.1:6969/add_urls
Content-Type: application/json

{
  "urls": ["https://www.gov.uk/guidance/funding-for-farmers"]
}

